# Generated by Django 5.1.2 on 2024-10-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0002_reporter_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('students', models.ManyToManyField(related_name='courses', to='go.student')),
            ],
        ),
    ]
